// Textos de la app — español rioplatense (voseo). Centralizados para mantener consistencia.

export const copy = {
  appName: "Prode Mundial 2026",
  tagline: "Pronosticá los partidos del Mundial y competí con tus amigos.",

  nav: {
    matches: "Partidos",
    groups: "Grupos",
    ranking: "Tabla",
    admin: "Admin",
    logout: "Cerrar sesión",
  },

  login: {
    title: "Entrá con tu mail",
    subtitle:
      "Escribí tu mail y te mandamos un link de acceso. Lo tocás y entrás — sin contraseñas.",
    emailLabel: "Tu mail",
    emailPlaceholder: "vos@ejemplo.com",
    emailHelp: "Te enviamos un link de acceso a este mail.",
    submit: "Enviame el link",
    sending: "Enviando…",
    sent: "¡Listo! Revisá tu mail y tocá el link para entrar. (Puede tardar un minuto; mirá también el spam.)",
    error: "No pudimos enviar el link. Probá de nuevo.",
  },

  onboarding: {
    title: "¿Cómo te decís?",
    subtitle: "Este es el nombre que van a ver tus amigos en la tabla.",
    nameLabel: "Tu nombre",
    namePlaceholder: "Ej: el Colo",
    submit: "Guardar y empezar",
  },

  groups: {
    title: "Tus grupos",
    empty: "Todavía no estás en ningún grupo. Creá uno o sumate con un código.",
    createTitle: "Creá un grupo",
    createSubtitle: "Sos el admin. Compartí el código para que se sumen tus amigos.",
    nameLabel: "Nombre del grupo",
    namePlaceholder: "Ej: Los del asado",
    createSubmit: "Crear grupo",
    joinTitle: "Sumate a un grupo",
    joinSubtitle: "Pegá el código de invitación que te pasaron.",
    codeLabel: "Código de invitación",
    codePlaceholder: "Ej: MUNDIAL26",
    joinSubmit: "Unirme",
    inviteCode: "Código de invitación",
    copyCode: "Copiar código",
    copied: "¡Copiado!",
    shareLink: "Compartir link",
    linkCopied: "¡Link copiado!",
    members: (n: number) => (n === 1 ? "1 jugador" : `${n} jugadores`),
    adminBadge: "Admin",
    viewRanking: "Ver tabla",
    alreadyMember: "Ya estás en este grupo.",
    invalidCode: "Ese código no existe. Fijate que esté bien escrito.",
  },

  perfil: {
    title: "Tu perfil",
    changePhoto: "Cambiar foto",
    uploading: "Subiendo…",
    nameLabel: "Tu nombre",
    save: "Guardar",
    saved: "¡Guardado!",
    notImage: "Tiene que ser una imagen.",
    tooBig: "La imagen es muy pesada (máx 3 MB).",
    uploadError: "No se pudo subir la foto. Probá de nuevo.",
  },

  easterEgg: {
    badge: "Bromista",
    title: "Poder de Bromista 🃏",
    desc: "Tenés un don único: podés cambiarle la foto a cualquiera de tus grupos. Usalo con sabiduría… o no 😈",
    empty: "Todavía no compartís grupo con nadie a quien embromar.",
    change: "Cambiar foto",
    changing: "Cambiando…",
  },

  matches: {
    title: "Partidos",
    subtitle: "Cargá tu resultado antes de que empiece cada partido.",
    yourPrediction: "Tu pronóstico",
    result: "Resultado",
    locked: "Cerrado",
    save: "Guardar",
    saved: "Guardado",
    saving: "Guardando…",
    points: (n: number) => (n === 1 ? "1 punto" : `${n} puntos`),
    noPrediction: "Sin pronóstico",
    closesAt: "Cierra al empezar el partido",
    openHint: "Abierto para cargar tu pronóstico",
    empty: "Todavía no hay partidos cargados. Volvé en un rato.",
    playedTitle: (n: number) => `Partidos jugados (${n})`,
    noUpcoming: "No hay próximos partidos.",
  },

  focus: {
    title: "Modo Focus",
    subtitle: "Un partido a la vez: tocá los goles de cada equipo.",
    enter: "Modo Focus",
    exit: "Ver lista",
    progress: (i: number, n: number) => `Partido ${i} de ${n}`,
    back: "Anterior",
    next: "Siguiente",
    finish: "Terminar",
    saving: "Guardando…",
    saved: "Guardado",
    tapToPick: "Tocá los goles de cada equipo",
    doneTitle: "¡Eso es todo!",
    doneSubtitle:
      "Pasaste por todos los partidos abiertos. Podés volver cuando quieras a retocar tus pronósticos.",
    backToList: "Volver a la lista",
    startOver: "Repasar de nuevo",
    empty: "No hay partidos abiertos para pronosticar ahora mismo.",
  },

  ranking: {
    title: "Tabla de posiciones",
    subtitle: "Se actualiza a medida que terminan los partidos.",
    position: "Pos",
    player: "Jugador",
    exact: "Exactos",
    points: "Puntos",
    empty: "Todavía nadie sumó puntos. ¡A jugar!",
    you: "vos",
  },

  player: {
    subtitle: "Pronósticos de los partidos que ya empezaron.",
    prediction: "Pronóstico",
    empty: "Todavía no hay pronósticos para mostrar.",
    totalPoints: (n: number) => (n === 1 ? "1 punto" : `${n} puntos`),
    backToRanking: "Volver a la tabla",
  },

  scoring: {
    title: "Cómo se puntúa",
    exact: "Resultado exacto",
    exactPts: "10 pts",
    outcomeOneSide: "Ganador/empate + goles de un equipo",
    outcomeOneSidePts: "7 pts",
    outcome: "Acertar ganador o empate",
    outcomePts: "5 pts",
    oneSide: "Solo los goles de un equipo",
    oneSidePts: "2 pts",
  },

  admin: {
    title: "Administración",
    syncNow: "Sincronizar partidos ahora",
    syncing: "Sincronizando…",
    lastSync: "Última sincronización",
    never: "Nunca",
    matchCount: (n: number) => `${n} partidos cargados`,
    syncDone: (n: number) => `Listo. ${n} partidos actualizados.`,
    notAdmin: "No tenés permisos de administrador.",
    editPredictions: "Editar pronósticos",
    editPredictionsDesc:
      "Cargá o corregí los pronósticos de cualquier jugador (incluso de partidos ya jugados). Útil para migrar de otra app.",
    pickMatch: "Elegí un partido",
    resultLabel: "Resultado",
    notFinishedYet: "Partido sin resultado todavía",
    savePredictions: "Guardar pronósticos",
    savingPredictions: "Guardando…",
    predictionsSaved: (n: number) => `Listo. ${n} pronósticos guardados.`,
    pointsCol: "Pts",
    users: "Usuarios",
    usersDesc: "Creá, editá o borrá jugadores. Podés pre-crearlos por mail para migrar.",
    createUser: "Crear usuario",
    emailLabel: "Mail",
    emailPlaceholder: "amigo@ejemplo.com",
    nameLabel: "Nombre",
    namePlaceholder: "Ej: el Colo",
    create: "Crear",
    creating: "Creando…",
    userCreated: "Usuario creado.",
    adminFlag: "Admin",
    save: "Guardar",
    saving: "Guardando…",
    saved: "Guardado",
    deleteUser: "Borrar",
    confirmDelete: (name: string) =>
      `¿Borrar a ${name}? Se borran también sus pronósticos. No se puede deshacer.`,
    you: "vos",
    noEmail: "(sin mail)",
    openForPlayers: "Abierto para que los jugadores carguen su pronóstico",
    openForPlayersHint:
      "Activalo para que cada uno complete su pronóstico de este partido (aunque ya se haya jugado).",
    resultTitle: "Resultado del partido",
    resultHint:
      "Si la API todavía no lo actualizó, cargalo a mano. Cuando llegue de la API, se usa el de la API.",
    saveResult: "Guardar resultado",
    clearResult: "Limpiar (que lo traiga la API)",
    resultSaved: "Resultado guardado.",
    resultFromApi: "Vino de la API.",
    resultFromManual: "Cargado a mano (la API lo va a pisar cuando lo tenga).",
  },

  stages: {
    GROUP: "Fase de grupos",
    LAST_32: "Dieciseisavos de final",
    LAST_16: "Octavos de final",
    QUARTER_FINAL: "Cuartos de final",
    SEMI_FINAL: "Semifinal",
    THIRD_PLACE: "Tercer puesto",
    FINAL: "Final",
  } as Record<string, string>,

  theme: {
    system: "Según el sistema",
    light: "Modo claro",
    dark: "Modo oscuro",
  } as Record<string, string>,

  common: {
    loading: "Cargando…",
    back: "Volver",
    vs: "vs",
  },
};
